routes/web.php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::prefix('client')->name('admin.')->group(function () {
    Route::get('/home/', [\App\Http\Controllers\Client\HomeController::class, 'index'])->name('home');
    Route::get('/user/{user}', [\App\Http\Controllers\Client\UserController::class, 'index'])->name('user');
});


Route::get('/', function () {
    return Inertia::render('Welcome', [
        'canLogin' => Route::has('login'),
        'canRegister' => Route::has('register'),
        'laravelVersion' => Application::VERSION,
        'phpVersion' => PHP_VERSION,
    ]);
});

Route::get('/dashboard', function () {
    return Inertia::render('Dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');


Route::prefix('/test')->name('test.')->group(function () {
    Route::post('/store', [\App\Http\Controllers\TestController::class, 'store'])
        ->name('store');
    Route::get('/', [\App\Http\Controllers\TestController::class, 'show'])
        ->name('show');
});


Route::match(['get', 'post'], '/demo', function () {
    echo "hello";
});

Route::get('/checkage/{age}', function () {
    echo '<h1>Xin chào</h1>';
})->middleware('custom');

Route::get('/post', function () {
    echo "successfully";
})->middleware('Role:editor');


Route::get('/data', function () {
    //    session()->put('buc','condai');
    //    return redirect()->action([\App\Http\Controllers\TestController::class,'show']);
    //    return redirect()->away('https://google.com');
    return redirect('/test')->with('nickname', 'Hoang Viet');
});

Route::get('/data2', function () {
    //    \Illuminate\Support\Facades\Session::flush();
    dd(\Illuminate\Support\Facades\Session::get('buc'));
});

Route::get('/dowloand', function () {
    return response()->download('../storage/app/public/demo.txt');
});

Route::get('/stream', function () {
    return response()->streamDownload(function () {
        echo 'Bui Hoang Viet';
    }, 'users.txt');
});

Route::get('/caps/{str}', function ($str) {
    dd(response()->caps($str));
});

Route::get('/child', function () {
    return view('child');
});
Route::get('/create', function () {
    return \Illuminate\Support\Facades\URL::signedRoute('change_password', ['user' => 1]);
});

Route::get('change_password/{user}', function (Request $request) {
    if (!$request->hasValidSignature()) {
        dd('Not pass');
    }
})->name('change_password');


Route::post('/post', [\App\Http\Controllers\TestController::class, 'store'])->name('post.create');

Route::get('/post/create', function () {
    return view('post');
});

Route::get('/exceiption', function () {
    throw new Exception('Error roi');
});

Route::get('/logging', function () {
    \Illuminate\Support\Facades\Log::warning('Ngay mai la thu 2');
});

Route::get('/artisan', function () {
    \Illuminate\Support\Facades\Artisan::call('mail:send', [

    ]);
});

Route::get('/event', function () {
    event(new \App\Events\MessageNotification('This is broadcast'));
});

Route::get('/listen', function () {
    return view('listen');
});

Route::get('/collection', function () {
    collect([1, 2, 3, 4])->firstOrFail(function ($value, $key) {
        return $value > 5;
    });

});

Route::get('/test/flash', [\App\Http\Controllers\TestFlashController::class, 'flash']);

Route::get('/test', function () {
    $redis = \Illuminate\Support\Facades\Redis::connection();
    $redis->del('vietkone@gmail.com');
//    dd(1);
});

//Route::get('/sendmail', [\App\Http\Controllers\EmailController::class,'sendMail']);

Route::get('/import', [\App\Http\Controllers\ExcelController::class,'showForm']);
Route::post('/import', [\App\Http\Controllers\ExcelController::class, 'import'])
    ->name('excel.store');

require __DIR__ . '/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title inertia>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ mix('css/app.css') }}">

        <!-- Scripts -->
        @routes
        <script src="{{ mix('js/app.js') }}" defer></script>
        @inertiaHead
    </head>
    <body class="font-sans antialiased">
        @inertia

        @env ('local')
            <script src="http://localhost:8080/js/bundle.js"></script>
        @endenv
    </body>
</html>

resources/views/child.blade.php
@extends('parent')

@section('content')
    <h1>My content</h1>
    @component('components.modal')
        viet
    @endcomponent
@endsection
@section('sidebar')
    @parent

    <ul>
        <li>Item 1</li>
        <li>Item 1</li>
    </ul>
@endsection

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/listen.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Document</title>
</head>
<body>
    <div id="app">

    </div>
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/parent.blade.php
<html>
<head>
    <title>Laravel</title>
</head>
<body>
    @section('sidebar')
        <h1>Sidebar</h1>
    @show

    @yield('content')
</body>
</html>

resources/views/post.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form method="post" action="{{route('post.create')}}">
        <label for="">Name</label>
        <input type="text" name="name"/>
        <button type="submit">Send</button>
    </form>
    @if($errors->any())
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    @endif
</body>
</html>

resources/views/time.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel Timezones</title>

    <link href="https://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">

    <style>
        html, body {
            height: 100%;
        }

        body {
            margin: 0;
            padding: 0;
            width: 100%;
            display: table;
            font-weight: 100;
            font-family: 'Lato';
        }

        .container {
            text-align: center;
            display: table-cell;
            vertical-align: middle;
        }

        .content {
            text-align: center;
            display: inline-block;
        }

        .title {
            font-size: 96px;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="content">
        <div class="title">{{ $current_time }}</div>
    </div>
</div>
</body>
</html>

resources/views/viewcustom.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <p>Hello, {{ session('nickname')}}</p>
    <form action="{{route('test.store')}}" method="post">
        @csrf
        <div>
            <label for="name">Name</label><br/>
            <input type="text" name="name" id="name" value="{{old('name')}}"/>
        </div>
        <label for="description">Description</label><br/>
        <textarea name="description" id="description" cols="30" rows="10">{{old('description')}}</textarea>
        <div>
            <button type="submit">Sent</button>
        </div>
    </form>
</body>
</html>